# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 13:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('prenom', models.CharField(max_length=100, verbose_name='pr\xe9nom')),
                ('adress', models.CharField(blank=True, max_length=100, null=True, verbose_name='adress')),
                ('zipcode', models.IntegerField(blank=True, null=True, verbose_name='zipcode')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='city')),
                ('email_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='email contact')),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(blank=True, max_length=100, null=True, verbose_name='adress')),
                ('zipcode', models.IntegerField(blank=True, null=True, verbose_name='zipcode')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='city')),
                ('email_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='email contact')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('montant', models.IntegerField(blank=True, null=True, verbose_name='montant')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturier.Client')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturier.Compte')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_facturation', models.DateField(auto_now_add=True)),
                ('montant', models.IntegerField(blank=True, null=True, verbose_name='montant')),
                ('date_validation', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='archive',
            name='devis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturier.Devis'),
        ),
    ]
