# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='devis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facturier.Devis'),
            preserve_default=False,
        ),
    ]
