# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0003_auto_20170619_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='descpt',
            field=models.CharField(default=1, max_length=200, verbose_name='descpt'),
            preserve_default=False,
        ),
    ]
