# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0005_devis_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='status',
            field=models.CharField(choices=[(1, 'In progress'), (2, 'paid')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
