# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 09:29
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0006_facture_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='title', unique_with=('title',)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devis',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='Mon super titre'),
            preserve_default=False,
        ),
    ]
