# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0007_auto_20170623_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
