# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 10:05
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0008_auto_20170623_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='name', unique_with=('name',)),
            preserve_default=False,
        ),
    ]
