# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0009_client_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='status',
            field=models.CharField(choices=[('1', 'In progress'), ('2', 'Refuse'), ('3', 'To win')], max_length=2),
        ),
    ]
