# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0010_auto_20170623_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='status',
            field=models.CharField(choices=[('1', 'In progress'), ('2', 'paid')], max_length=2),
        ),
    ]
