# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 12:05
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0011_auto_20170630_0800'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('title',))),
                ('descpt', models.CharField(max_length=200, verbose_name='descpt')),
                ('prix', models.IntegerField(blank=True, null=True, verbose_name='montant')),
            ],
        ),
        migrations.RemoveField(
            model_name='devis',
            name='descpt',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='devis',
            name='title',
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='devis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturier.Devis'),
        ),
    ]
