# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 12:14
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0012_auto_20170703_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignedevis',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='lignedevis',
            name='title',
        ),
        migrations.AddField(
            model_name='devis',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='title', unique_with=('title',)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devis',
            name='title',
            field=models.CharField(default=2, max_length=100, verbose_name='title'),
            preserve_default=False,
        ),
    ]
