# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0013_auto_20170703_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignedevis',
            name='prix',
            field=models.IntegerField(blank=True, null=True, verbose_name='prix'),
        ),
    ]
