# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 13:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0016_auto_20170703_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='montant',
        ),
        migrations.AddField(
            model_name='devis',
            name='montant',
            field=models.IntegerField(blank=True, null=True, verbose_name='montant'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_validation',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
