# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 09:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0017_auto_20170706_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='date_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='qty'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='devis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturier.Devis'),
        ),
    ]
