# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0018_auto_20170710_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='date_creation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
