# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0019_auto_20170710_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='title'),
            preserve_default=False,
        ),
    ]
