# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0022_auto_20170710_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='date_facturation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
